### ISSUE TITLE
LoadData doesn't merge configs like LoadFiles

### ISSUE THREAD

**Issue by Adzikus** [gookit/config#166]
**System (please complete the following information):**

 - OS: `windows`
 - GO Version: `1.20`
 - Pkg Version: `2.2.3`

**Describe the bug**

When loading config from Files 
```go
paths := []string{"base.json", "mod.json"}
err = tmpCfg.LoadFiles(paths...)
```
configuration is appended but when using `LoadData()` is overriding by last source

**To Reproduce**

```go
// MODELS

type PostgresConfig struct {
// cut for simplicity
	Postgres *Postgres
}

type Postgres struct {
	Host         string
	Port         int
	User         string
	Password     string
	PasswordFile string
	Database     string
	SearchPath   string
	MinPoolSize  int32
	MaxPoolSize  int32 
}

// GOT
initConfig := map[string]any{
 "Postgres": &Postgres{
 Host:         "init-host",
 Port:         1000,
 User:         "init-user",
 Password:     "init-password",
 PasswordFile: "init-password-file",
 Database:     "init-database",
 SearchPath:   "init-search-path",
 MinPoolSize:  10,
 MaxPoolSize:  100,
 }}
appendConfig := map[string]any{
 "Postgres": &Postgres{Host: "append-host"}}

cfg := config.New("")
result := &PostgresConfig{}
cfg.LoadData(initConfig, appendConfig)
cfg.Decode(result)
```

**Current behavior**

![image](https://github.com/gookit/config/assets/48260917/91cb619d-e354-457d-90a7-e6657e223c89)

**Expected behavior**

`LoadData` Merges all data loaded by parameter list
![image](https://github.com/gookit/config/assets/48260917/2c38ea0e-1ddb-4a84-a694-ffb31b6bb05e)

**Additional context**

If needed some more explanation, code or screens, fell free to write.
If there is any other method to load data like from files but from source maps or maybe there is possibility to create something like `Merge(any...)`

**Comment by yz3358** [comment]
I don't think this is a bug. The equivalent of LoadData here should be loading map[string]any, without pointer. Becasue when you create struct, zero values are assigned automatically.

When LoadFile, contents are converted to map[string]any instead of a predefined struct. 

LoadData uses `mergo.Merge(..., merge.WithOverride)`. It will override "non-empty" attributes, which is desired in most use cases. (e.g. intentional override some int field to 0). 

I did not find a way to differentiate "user assigned zero value" vs "automatic zero value" in a struct. If there is, then adding a custom `mergo.Transformers` might do.

**Comment by inhere** [comment]
hi @yz3358 @Adzikus On https://github.com/gookit/config/releases/tag/v2.2.5, add new option: MergeOptions support custom the data merge options
